import type { ReactNode } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CheckCircle2, CircleAlert, Clock3, DatabaseZap, Gauge, ShieldCheck, ShieldX, WalletCards } from "lucide-react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ExecutionEvent, Position, Snapshot } from "../types";
import type { EquityPoint } from "../lib/equity-series";
import { Panel, StatusPill } from "./ui/terminal";

const decimal = new Intl.NumberFormat("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const signedMoney = (value: number) => `${value >= 0 ? "+" : ""}${decimal.format(value)} U`;
const money = (value: number) => `${decimal.format(value)} U`;
const eventNames: Record<ExecutionEvent["type"], string> = { open: "开仓成交", close: "平仓完成", reduce: "减仓执行", risk: "风控动作", sync: "状态同步" };

export function CommandCenter({ snapshot }: { snapshot: Snapshot }) {
  const riskRatio = snapshot.riskLimit ? Math.min(100, (snapshot.riskUsed / snapshot.riskLimit) * 100) : 0;
  const isStale = snapshot.dataAgeSeconds > 30 || snapshot.monitor.status !== "ok";
  const protectedCount = snapshot.positions.filter((position) => position.protected).length;
  const latestEvents = snapshot.executionEvents.slice(0, 5);
  const warnings = snapshot.executionEvents.filter((event) => event.type === "risk").slice(0, 2);
  const grossExposure = snapshot.positions.reduce((total, position) => total + position.notional, 0);
  const equityLabel = snapshot.dataMode === "live_read_only" ? "Bybit账户净值" : "模拟净值";
  const equityBasis = snapshot.dataMode === "live_read_only"
    ? "口径：策略资金账本 + 当前持仓浮盈亏"
    : "模拟数据，不代表 Bybit 账户余额";

  return <div className="space-y-3">
    <div className="grid gap-3 xl:grid-cols-[1.45fr_.55fr]">
      <Panel className="overflow-hidden border-t-2 border-t-terminal-teal/55">
        <PanelHeader eyebrow="策略资金" title="组合表现" trailing={<StatusPill tone={snapshot.dataMode === "live_read_only" ? "positive" : "warning"}>{snapshot.dataMode === "live_read_only" ? "实盘镜像" : "模拟回退"}</StatusPill>} />
        <div className="grid min-h-[228px] lg:grid-cols-[220px_1fr]">
          <div className="border-b border-terminal-line p-4 lg:border-b-0 lg:border-r">
            <p className="text-[11px] text-terminal-muted">{equityLabel}</p>
            <p className="mt-2 text-[30px] font-semibold leading-none tabular-nums text-terminal-text">{decimal.format(snapshot.equity)}<span className="ml-2 text-sm font-medium text-terminal-muted">U</span></p>
            <p className="mt-2 text-[9px] leading-4 text-terminal-faint">{equityBasis}</p>
            <div className={`mt-4 inline-flex items-center gap-1.5 font-mono text-sm font-semibold tabular-nums ${snapshot.dailyPnl >= 0 ? "text-terminal-up" : "text-terminal-down"}`}>{snapshot.dailyPnl >= 0 ? <ArrowUpRight size={15} aria-hidden="true" /> : <ArrowDownRight size={15} aria-hidden="true" />}{signedMoney(snapshot.dailyPnl)}</div>
            <p className="mt-1 text-[10px] text-terminal-faint">策略运行期变化</p>
            <div className="mt-5 flex items-end justify-between border-t border-terminal-line pt-3"><div><p className="text-[10px] text-terminal-muted">最大回撤</p><p className="mt-1 font-mono text-sm font-semibold tabular-nums text-terminal-warn">{snapshot.drawdown.toFixed(2)}%</p></div><div className="text-right"><p className="text-[10px] text-terminal-muted">数据延迟</p><p className={`mt-1 font-mono text-sm font-semibold tabular-nums ${isStale ? "text-terminal-warn" : "text-terminal-up"}`}>{snapshot.dataAgeSeconds}s</p></div></div>
          </div>
          <div className="min-w-0 p-3 sm:p-4"><div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-[10px] text-terminal-muted">账户净值轨迹</p><p className="mt-0.5 text-[9px] text-terminal-faint">服务端实盘净值历史</p></div><span className="shrink-0 font-mono text-[9px] tabular-nums text-terminal-faint">{snapshot.equitySeries.length} 个采样</span></div><div className="h-[164px] w-full"><EquityChart points={snapshot.equitySeries} label={equityLabel} /></div></div>
        </div>
        <div className="grid grid-cols-2 gap-px border-t border-terminal-line bg-terminal-line sm:grid-cols-4"><SummaryCell label="名义敞口" value={money(grossExposure)} detail={`${snapshot.positions.length} 个持仓`} /><SummaryCell label="风险使用" value={`${snapshot.riskUsed.toFixed(1)} U`} detail={`${riskRatio.toFixed(0)}% 预算`} tone={riskRatio >= 80 ? "warning" : "default"} /><SummaryCell label="可用风险" value={money(Math.max(0, snapshot.riskLimit - snapshot.riskUsed))} detail={`上限 ${snapshot.riskLimit.toFixed(0)} U`} /><SummaryCell label="保护覆盖" value={`${protectedCount}/${snapshot.positions.length}`} detail="reduceOnly" tone={protectedCount === snapshot.positions.length ? "positive" : "negative"} /></div>
      </Panel>

      <Panel className="overflow-hidden border-t-2 border-t-terminal-warn/55">
        <PanelHeader eyebrow="实时风控" title="风险态势" trailing={<Gauge size={17} className={riskRatio >= 80 ? "text-terminal-warn" : "text-terminal-up"} aria-hidden="true" />} />
        <div className="p-4"><div className="flex items-end justify-between"><div><p className="text-[11px] text-terminal-muted">组合止损风险</p><p className={`mt-1 font-mono text-2xl font-semibold tabular-nums ${riskRatio >= 80 ? "text-terminal-warn" : "text-terminal-text"}`}>{riskRatio.toFixed(0)}%</p></div><p className="font-mono text-xs text-terminal-muted">{snapshot.riskUsed.toFixed(1)} / {snapshot.riskLimit.toFixed(0)} U</p></div><div className="mt-3 h-1.5 overflow-hidden bg-terminal-line" role="progressbar" aria-label="组合风险预算使用率" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(riskRatio)}><div className={`h-full ${riskRatio >= 80 ? "bg-terminal-warn" : "bg-terminal-up"}`} style={{ width: `${riskRatio}%` }} /></div>
          <div className="mt-5 divide-y divide-terminal-line border-y border-terminal-line"><HealthRow label="执行器" value={snapshot.botMode === "running" ? "运行中" : "受限"} ok={snapshot.botMode === "running"} /><HealthRow label="保护单" value={`${protectedCount}/${snapshot.positions.length}`} ok={protectedCount === snapshot.positions.length} /><HealthRow label="数据连接" value={isStale ? "需核对" : "正常"} ok={!isStale} /><HealthRow label="待决意图" value={`${snapshot.pendingIntents}`} ok={snapshot.pendingIntents === 0} /></div>
          <div className={`mt-4 flex items-start gap-2 rounded-[5px] border p-3 ${riskRatio >= 80 ? "border-terminal-warn/30 bg-terminal-warn/7" : "border-terminal-up/25 bg-terminal-up/6"}`}><ShieldCheck size={14} className={`mt-0.5 shrink-0 ${riskRatio >= 80 ? "text-terminal-warn" : "text-terminal-up"}`} aria-hidden="true" /><p className="text-[11px] leading-5 text-terminal-muted">{riskRatio >= 80 ? "风险预算已接近上限，新仓准入应保持谨慎。" : "风险预算充足，当前仓位保护状态正常。"}</p></div>
        </div>
      </Panel>
    </div>

    <div className="grid gap-3 xl:grid-cols-[1.45fr_.55fr]">
      <Panel className="overflow-hidden border-t-2 border-t-terminal-blue/55"><PanelHeader eyebrow="交易所镜像" title="当前持仓" trailing={<StatusPill tone={protectedCount === snapshot.positions.length ? "positive" : "negative"}><ShieldCheck size={11} aria-hidden="true" />保护 {protectedCount}/{snapshot.positions.length}</StatusPill>} />{snapshot.positions.length === 0 ? <EmptyPositions /> : <><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-terminal-soft/70 text-terminal-muted"><tr>{["标的", "方向", "名义仓位", "入场价", "标记价", "未实现盈亏", "止损保护"].map((title) => <th className="px-4 py-2.5 font-medium" key={title}>{title}</th>)}</tr></thead><tbody>{snapshot.positions.map((position) => <PositionRow key={position.id} position={position} />)}</tbody></table></div><div className="divide-y divide-terminal-line sm:hidden">{snapshot.positions.map((position) => <MobilePosition key={position.id} position={position} />)}</div></>}</Panel>
      <Panel className="overflow-hidden border-t-2 border-t-terminal-down/45"><PanelHeader eyebrow="需要关注" title="执行异常" trailing={<CircleAlert size={17} className={isStale || snapshot.blockers.length ? "text-terminal-warn" : "text-terminal-up"} aria-hidden="true" />} /><div className="divide-y divide-terminal-line">{isStale ? <AlertRow icon={<Clock3 size={14} />} title="行情或监控数据陈旧" detail={`最近快照已过去 ${snapshot.dataAgeSeconds} 秒，请核对连接。`} tone="warning" /> : null}{snapshot.dataMode !== "live_read_only" ? <AlertRow icon={<DatabaseZap size={14} />} title="正在使用模拟回退" detail="实时只读快照不可用，当前指标不代表实盘账户。" tone="warning" /> : null}{snapshot.blockers.slice(0, 2).map((blocker) => <AlertRow key={blocker} icon={<ShieldX size={14} />} title="执行准入已阻断" detail={blocker.replaceAll("_", " ")} tone="negative" />)}{warnings.map((event) => <AlertRow key={event.id} icon={<AlertTriangle size={14} />} title={eventNames[event.type]} detail={`${event.symbol} · ${event.reason}`} tone="warning" />)}{!isStale && snapshot.dataMode === "live_read_only" && snapshot.blockers.length === 0 && warnings.length === 0 ? <AlertRow icon={<CheckCircle2 size={14} />} title="当前无执行异常" detail="持仓、风控与执行管线均已更新。" tone="positive" /> : null}</div></Panel>
    </div>

    <Panel className="overflow-hidden"><PanelHeader eyebrow="审计流水" title="最近执行" trailing={<span className="font-mono text-[10px] text-terminal-muted">待决 {snapshot.pendingIntents}</span>} /><div className="grid divide-y divide-terminal-line md:grid-cols-5 md:divide-x md:divide-y-0">{latestEvents.length ? latestEvents.map((event) => <div className="min-w-0 px-4 py-3" key={event.id}><div className="flex items-center gap-2"><span className={`h-1.5 w-1.5 ${event.type === "risk" ? "bg-terminal-warn" : event.type === "open" ? "bg-terminal-up" : "bg-terminal-blue"}`} /><span className="font-mono text-[10px] tabular-nums text-terminal-faint">{event.time}</span></div><p className="mt-2 truncate text-xs font-medium text-terminal-text">{eventNames[event.type]} · {event.symbol}</p><p className="mt-1 truncate text-[10px] text-terminal-muted" title={event.reason}>{event.reason}</p></div>) : <p className="px-4 py-5 text-xs text-terminal-muted">暂无执行记录</p>}</div></Panel>
  </div>;
}

function PanelHeader({ eyebrow, title, trailing }: { eyebrow: string; title: string; trailing?: ReactNode }) { return <div className="flex min-h-[58px] items-center justify-between gap-3 border-b border-terminal-line px-4 py-3"><div className="min-w-0"><p className="section-kicker">{eyebrow}</p><h2 className="mt-1 truncate text-sm font-semibold text-terminal-text">{title}</h2></div>{trailing}</div>; }
function SummaryCell({ label, value, detail, tone = "default" }: { label: string; value: string; detail: string; tone?: "default" | "positive" | "negative" | "warning" }) { const colors = { default: "text-terminal-text", positive: "text-terminal-up", negative: "text-terminal-down", warning: "text-terminal-warn" }; return <div className="bg-terminal-panel px-4 py-3"><p className="text-[10px] text-terminal-muted">{label}</p><p className={`mt-1 font-mono text-sm font-semibold tabular-nums ${colors[tone]}`}>{value}</p><p className="mt-0.5 text-[9px] text-terminal-faint">{detail}</p></div>; }
function HealthRow({ label, value, ok }: { label: string; value: string; ok: boolean }) { return <div className="flex items-center justify-between py-2.5 text-xs"><span className="text-terminal-muted">{label}</span><span className={`inline-flex items-center gap-1.5 font-medium ${ok ? "text-terminal-up" : "text-terminal-warn"}`}><span className={`h-1.5 w-1.5 ${ok ? "bg-terminal-up" : "bg-terminal-warn"}`} />{value}</span></div>; }
function PositionRow({ position }: { position: Position }) { return <tr className="border-t border-terminal-line/75 hover:bg-terminal-soft/45"><td className="px-4 py-3 font-mono font-semibold text-terminal-text">{position.symbol}</td><td className={`px-4 py-3 font-mono ${position.side === "long" ? "text-terminal-up" : "text-terminal-down"}`}>{position.side === "long" ? "多" : "空"} · {position.leverage}x</td><td className="px-4 py-3 font-mono tabular-nums text-terminal-text">{money(position.notional)}</td><td className="px-4 py-3 font-mono tabular-nums text-terminal-muted">{position.entryPrice.toFixed(4)}</td><td className="px-4 py-3 font-mono tabular-nums text-terminal-text">{position.markPrice.toFixed(4)}</td><td className={`px-4 py-3 font-mono font-semibold tabular-nums ${position.unrealizedPnl >= 0 ? "text-terminal-up" : "text-terminal-down"}`}>{signedMoney(position.unrealizedPnl)}</td><td className="px-4 py-3">{position.protected ? <span className="inline-flex items-center gap-1.5 text-terminal-up"><ShieldCheck size={13} aria-hidden="true" />有效</span> : <span className="inline-flex items-center gap-1.5 text-terminal-down"><ShieldX size={13} aria-hidden="true" />缺失</span>}</td></tr>; }
function MobilePosition({ position }: { position: Position }) { return <div className="p-4"><div className="flex items-start justify-between"><div><p className="font-mono text-sm font-semibold text-terminal-text">{position.symbol}</p><p className={`mt-1 font-mono text-[11px] ${position.side === "long" ? "text-terminal-up" : "text-terminal-down"}`}>{position.side === "long" ? "多" : "空"} · {position.leverage}x</p></div><p className={`font-mono text-sm font-semibold ${position.unrealizedPnl >= 0 ? "text-terminal-up" : "text-terminal-down"}`}>{signedMoney(position.unrealizedPnl)}</p></div><div className="mt-3 grid grid-cols-3 gap-3 border-t border-terminal-line pt-3"><MiniValue label="名义仓位" value={money(position.notional)} /><MiniValue label="标记价" value={position.markPrice.toFixed(4)} /><MiniValue label="止损" value={position.stopPrice.toFixed(4)} /></div></div>; }
function MiniValue({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-[9px] text-terminal-faint">{label}</p><p className="mt-1 truncate font-mono text-[11px] tabular-nums text-terminal-text">{value}</p></div>; }
function AlertRow({ icon, title, detail, tone }: { icon: ReactNode; title: string; detail: string; tone: "positive" | "warning" | "negative" }) { const colors = { positive: "text-terminal-up", warning: "text-terminal-warn", negative: "text-terminal-down" }; return <div className="flex gap-3 px-4 py-3"><span className={`mt-0.5 shrink-0 ${colors[tone]}`} aria-hidden="true">{icon}</span><div className="min-w-0"><p className="text-xs font-medium text-terminal-text">{title}</p><p className="mt-1 break-words text-[10px] leading-4 text-terminal-muted">{detail}</p></div></div>; }
function EquityChart({ points, label }: { points: EquityPoint[]; label: string }) {
  if (points.length < 2) {
    const point = points[0];
    return <div className="relative grid h-full place-items-center overflow-hidden border-y border-terminal-line bg-terminal-bg/25"><span className="absolute inset-x-4 top-1/2 border-t border-dashed border-terminal-teal/35" /><span className="absolute left-1/2 top-1/2 h-2.5 w-2.5 -translate-x-1/2 -translate-y-1/2 border-2 border-terminal-bg bg-terminal-teal shadow-[0_0_0_3px_rgba(79,209,165,.16)]" /><div className="relative mt-16 text-center"><p className="font-mono text-xs font-semibold tabular-nums text-terminal-text">{point ? `${decimal.format(point.equity)} U` : "--"}</p><p className="mt-1 text-[9px] text-terminal-muted">起始快照已记录，等待下一次刷新形成轨迹</p></div></div>;
  }
  const values = points.map((point) => point.equity);
  const minimum = Math.min(...values);
  const maximum = Math.max(...values);
  const padding = Math.max((maximum - minimum) * 0.35, maximum * 0.0002, 0.12);
  const baseline = points[0].equity;
  return <ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><CartesianGrid vertical={false} stroke="#28333c" strokeDasharray="2 5" /><XAxis dataKey="time" tickLine={false} axisLine={false} minTickGap={38} tick={{ fill: "#73818c", fontSize: 9 }} /><YAxis width={52} tickLine={false} axisLine={false} domain={[minimum - padding, maximum + padding]} tickCount={3} tickFormatter={(value) => decimal.format(Number(value))} tick={{ fill: "#73818c", fontSize: 9 }} /><ReferenceLine y={baseline} stroke="#53616c" strokeDasharray="4 4" /><Tooltip contentStyle={{ background: "#0c1218", border: "1px solid #36434d", borderRadius: 5, fontSize: 11 }} labelStyle={{ color: "#91a0ac", marginBottom: 4 }} formatter={(value) => [`${decimal.format(Number(value))} U`, label]} /><Line type="linear" dataKey="equity" stroke="#4fd1a5" strokeWidth={2} dot={{ r: 2, fill: "#4fd1a5", strokeWidth: 0 }} activeDot={{ r: 4, fill: "#4fd1a5", stroke: "#0b1015", strokeWidth: 2 }} isAnimationActive={false} /></LineChart></ResponsiveContainer>;
}
function EmptyPositions() { return <div className="grid min-h-40 place-items-center px-6 text-center"><div><WalletCards size={20} className="mx-auto text-terminal-faint" aria-hidden="true" /><p className="mt-2 text-sm text-terminal-text">当前无已对账持仓</p><p className="mt-1 text-[11px] text-terminal-muted">等待交易所账户与执行状态同步</p></div></div>; }
