import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, ShieldCheck } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { motion } from "framer-motion";
import type { Snapshot } from "../types";
import { Panel, Stat, StatusPill } from "./ui/terminal";

const tooltipStyle = { background: "#10161e", border: "1px solid #2b3b49", borderRadius: 0, color: "#dce7ef", fontSize: 11 };

export function PortfolioOverview({ snapshot }: { snapshot: Snapshot }) {
  const available = Math.max(0, snapshot.riskLimit - snapshot.riskUsed);
  const radius = 41;
  const circumference = 2 * Math.PI * radius;
  const progress = Math.max(0, Math.min(1, snapshot.riskUsed / Math.max(snapshot.riskLimit, 1)));
  return <div className="grid gap-3 xl:grid-cols-[1.45fr_1fr_.78fr]">
    <Panel className="min-h-[268px] p-4">
      <div className="flex items-start justify-between"><div><p className="section-kicker">Bybit账户净值</p><div className="mt-1 flex items-baseline gap-2"><motion.span key={snapshot.equity} initial={{ opacity: 0.5 }} animate={{ opacity: 1 }} className="font-mono text-[27px] font-semibold tabular-nums text-terminal-text">{snapshot.equity.toFixed(2)} U</motion.span><span className={snapshot.dailyPnl >= 0 ? "text-xs text-terminal-up" : "text-xs text-terminal-down"}>{snapshot.dailyPnl >= 0 ? <ArrowUpRight size={13} className="inline" /> : <ArrowDownRight size={13} className="inline" />}{snapshot.dailyPnl >= 0 ? "+" : ""}{snapshot.dailyPnl.toFixed(2)} U</span></div></div><StatusPill tone={snapshot.botMode === "running" ? "positive" : "warning"}><Activity size={10} />{snapshot.botMode === "running" ? "运行中" : "准入阻断"}</StatusPill></div>
      <div className="mt-5 h-[150px]">{snapshot.equitySeries.length > 1 ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={snapshot.equitySeries}><defs><linearGradient id="equityShade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#29c8a1" stopOpacity="0.28" /><stop offset="1" stopColor="#29c8a1" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#24303c" strokeDasharray="2 4" /><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{ fill: "#718192", fontSize: 10 }} /><YAxis hide /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`${Number(value).toFixed(2)} U`, "净值"]} /><Area dataKey="equity" type="monotone" stroke="#29c8a1" strokeWidth={1.6} fill="url(#equityShade)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center border-y border-terminal-line text-center"><div><p className="font-mono text-sm text-terminal-text">仅当前实盘快照</p><p className="mt-1 text-xs text-terminal-muted">历史净值序列尚未接入</p></div></div>}</div>
      <div className="mt-2 grid grid-cols-3 border-t border-terminal-line pt-3"><Stat label="策略变化" value={`${snapshot.dailyPnl >= 0 ? "+" : ""}${snapshot.dailyPnl.toFixed(2)} U`} tone={snapshot.dailyPnl >= 0 ? "positive" : "negative"} /><Stat label="最大回撤" value={`${snapshot.drawdown.toFixed(2)}%`} tone="warning" /><Stat label="策略状态" value={snapshot.botMode === "running" ? "验证运行" : "准入阻断"} tone={snapshot.botMode === "running" ? "positive" : "warning"} /></div>
    </Panel>
    <Panel className="min-h-[268px] p-4">
      <div className="flex items-start justify-between"><div><p className="section-kicker">策略变化与回撤</p><p className="mt-1 text-xs text-terminal-muted">基于服务端实盘净值快照</p></div><span className="font-mono text-xs text-terminal-faint">UTC+8</span></div>
      <div className="mt-5 h-[150px]">{snapshot.equitySeries.length > 1 ? <ResponsiveContainer width="100%" height="100%"><LineChart data={snapshot.equitySeries}><CartesianGrid vertical={false} stroke="#24303c" strokeDasharray="2 4" /><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{ fill: "#718192", fontSize: 10 }} /><YAxis hide /><Tooltip contentStyle={tooltipStyle} /><Line type="stepAfter" dataKey="pnl" stroke="#52b9e9" strokeWidth={1.5} dot={false} /><Line type="monotone" dataKey="drawdown" stroke="#e6b95d" strokeWidth={1.2} strokeDasharray="3 3" dot={false} /></LineChart></ResponsiveContainer> : <div className="grid h-full place-items-center border-y border-terminal-line text-center"><div><p className="font-mono text-sm text-terminal-text">{snapshot.dailyPnl >= 0 ? "+" : ""}{snapshot.dailyPnl.toFixed(2)} U</p><p className="mt-1 text-xs text-terminal-muted">当前日内盈亏</p></div></div>}</div>
      <div className="mt-2 flex gap-4 border-t border-terminal-line pt-3 text-[10px]"><span className="flex items-center gap-1 text-terminal-muted"><i className="h-1.5 w-1.5 bg-terminal-blue" />策略变化</span><span className="flex items-center gap-1 text-terminal-muted"><i className="h-1.5 w-1.5 bg-terminal-warn" />回撤</span><span className="ml-auto text-terminal-faint">无历史回测曲线混入</span></div>
    </Panel>
    <Panel className="relative min-h-[268px] overflow-hidden p-4">
      <div><p className="section-kicker">组合止损风险</p><p className="mt-1 text-xs text-terminal-muted">跨仓累计理论损失上限</p></div>
      <div className="mt-2 grid place-items-center"><svg viewBox="0 0 110 110" className="h-[135px] w-[135px] -rotate-90"><circle cx="55" cy="55" r={radius} fill="none" stroke="#1e2b35" strokeWidth="9" /><motion.circle cx="55" cy="55" r={radius} fill="none" stroke="#e1b252" strokeWidth="9" strokeLinecap="butt" strokeDasharray={circumference} initial={{ strokeDashoffset: circumference }} animate={{ strokeDashoffset: circumference * (1 - progress) }} transition={{ duration: 0.55 }} /></svg><div className="absolute mt-[68px] text-center"><p className="font-mono text-2xl font-semibold tabular-nums text-terminal-warn">{snapshot.riskUsed.toFixed(2)}U</p><p className="text-[10px] text-terminal-muted">/ {snapshot.riskLimit.toFixed(0)}U</p></div></div>
      <div className="mt-0 flex items-center justify-between border-t border-terminal-line pt-3"><span className="text-xs text-terminal-muted">剩余预算</span><span className="font-mono text-sm text-terminal-warn">{available.toFixed(0)}U</span></div>
      <div className="mt-2 flex items-start gap-1.5 text-[11px] leading-4 text-terminal-warn"><AlertTriangle size={12} className="mt-0.5 shrink-0" />当前 {snapshot.positions.length} 个持仓合计占用 {snapshot.riskUsed.toFixed(2)}U 理论止损风险。</div>
    </Panel>
    <div className="xl:col-span-3 grid gap-3 md:grid-cols-3">
      {[{ label: "执行器", value: snapshot.botMode === "running" ? "运行中" : "已阻断", detail: snapshot.executionStatus, icon: Activity, tone: snapshot.botMode === "running" ? "positive" : "warning" }, { label: "仓位策略", value: `${snapshot.positions.length} / ${snapshot.minimumOpenPositions} / ${snapshot.maxOpenPositions}`, detail: "当前 / 最低 / 上限", icon: ShieldCheck, tone: snapshot.positions.length >= snapshot.minimumOpenPositions ? "positive" : "warning" }, { label: "执行锁", value: snapshot.pendingIntents ? `${snapshot.pendingIntents} 个未决` : "无未决订单", detail: `累计实盘订单 ${snapshot.realOrdersSent}`, icon: AlertTriangle, tone: snapshot.pendingIntents ? "warning" : "positive" }].map(({ label, value, detail, icon: Icon, tone }) => <Panel key={label} className="flex items-center gap-3 p-3"><div className="grid h-9 w-9 place-items-center border border-terminal-line bg-terminal-soft text-terminal-teal"><Icon size={15} /></div><div className="min-w-0"><p className="text-[11px] text-terminal-muted">{label}</p><p className="mt-0.5 truncate font-mono text-sm text-terminal-text">{value}</p><p className="mt-0.5 text-[11px] text-terminal-faint">{detail}</p></div><span className={tone === "warning" ? "ml-auto h-1.5 w-1.5 bg-terminal-warn" : "ml-auto h-1.5 w-1.5 bg-terminal-up"} /></Panel>)}
    </div>
  </div>;
}
