import { AlertTriangle, Check, Clock3, Lock, ShieldAlert, ShieldCheck } from "lucide-react";
import type { Snapshot } from "../types";
import { Panel, Stat, StatusPill } from "./ui/terminal";

export function RiskCenter({ snapshot }: { snapshot: Snapshot }) {
  const remaining = Math.max(0, snapshot.riskLimit - snapshot.riskUsed);
  const elite = snapshot.eliteCore;
  const eliteFits = elite.status === "eligible" && remaining + 0.01 >= elite.riskUsdt;
  const signalFits = remaining >= 40;
  return <div className="grid gap-3 xl:grid-cols-[1.1fr_.9fr]">
    <Panel className="p-4"><div className="flex items-start justify-between"><div><p className="section-kicker">风险中心</p><p className="mt-1 text-xs text-terminal-muted">实盘准入基于已对账持仓、交易所保护单与组合风险预算。</p></div><div className="flex items-center gap-2"><StatusPill tone="info">仓位 {snapshot.positions.length} / {snapshot.maxOpenPositions}</StatusPill><StatusPill tone={snapshot.botMode === "running" ? "positive" : "warning"}><ShieldCheck size={10} />{snapshot.botMode === "running" ? "风险受控" : "需要复核"}</StatusPill></div></div>
      <div className="mt-4 grid grid-cols-2 gap-px border border-terminal-line bg-terminal-line sm:grid-cols-4">{[{ label: "组合止损风险", value: `${snapshot.riskUsed.toFixed(2)} / ${snapshot.riskLimit.toFixed(0)}U`, hint: "逐仓 reduceOnly" }, { label: "剩余风险预算", value: `${remaining.toFixed(2)}U`, hint: "新仓硬上限" }, { label: "连续亏损", value: "0 / 3", hint: "两连亏普通仓减半" }, { label: "当日熔断", value: "0.00 / 50U", hint: "日损 5%" }].map((item) => <div key={item.label} className="bg-terminal-panel p-3"><Stat {...item} /></div>)}</div>
      <div className="mt-4"><p className="section-kicker">五槽位配置</p><div className="mt-2 grid gap-2"><div className={eliteFits ? "flex items-center justify-between border border-terminal-up/30 bg-terminal-up/5 p-3" : "flex items-center justify-between border border-terminal-warn/40 bg-terminal-warn/5 p-3"}><div className="flex items-center gap-2">{eliteFits ? <Check size={15} className="text-terminal-up" /> : <Lock size={15} className="text-terminal-warn" />}<div><p className="text-xs text-terminal-text">高权重 / BTC ETH 核心仓 {elite.symbol}</p><p className="mt-0.5 text-[10px] text-terminal-muted">200U 保证金 / 5x / {elite.plannedNotional || 1000}U 名义 / 理论止损 {elite.riskUsdt || 40}U</p></div></div><span className={eliteFits ? "font-mono text-xs text-terminal-up" : "font-mono text-xs text-terminal-warn"}>{eliteFits ? "可容纳" : "等待条件"}</span></div><div className={signalFits ? "flex items-center justify-between border border-terminal-up/30 bg-terminal-up/5 p-3" : "flex items-center justify-between border border-terminal-warn/40 bg-terminal-warn/5 p-3"}><div className="flex items-center gap-2">{signalFits ? <Check size={15} className="text-terminal-up" /> : <Lock size={15} className="text-terminal-warn" />}<div><p className="text-xs text-terminal-text">三个信号仓</p><p className="mt-0.5 text-[10px] text-terminal-muted">每仓 200U 保证金 / 5x / 1000U 名义 / 理论止损 40U</p></div></div><span className={signalFits ? "font-mono text-xs text-terminal-up" : "font-mono text-xs text-terminal-warn"}>{signalFits ? "可容纳" : "等待信号"}</span></div></div></div>
      <div className="mt-4 grid gap-2 border-t border-terminal-line pt-4 text-[11px] text-terminal-muted"><div className="flex justify-between"><span>单日损失熔断</span><b className="font-mono font-medium text-terminal-text">5.00%</b></div><div className="flex justify-between"><span>相对峰值回撤</span><b className="font-mono font-medium text-terminal-text">15.00% / 停机复盘</b></div><div className="flex justify-between"><span>保护止损</span><b className="font-mono font-medium text-terminal-text">每笔全量 reduceOnly / 4.00%</b></div></div>
    </Panel>
    <Panel className="p-4"><div className="flex items-center justify-between"><div><p className="section-kicker">风险事件时间线</p><p className="mt-1 text-xs text-terminal-muted">最新状态与准入阻断原因</p></div><ShieldAlert size={17} className="text-terminal-warn" /></div><ol className="mt-5">{snapshot.riskEvents.map((event, index) => <li key={`${event.time}-${event.title}`} className="relative flex gap-3 pb-5 last:pb-0"><span className={`z-10 mt-0.5 grid h-5 w-5 place-items-center border border-terminal-line bg-terminal-panel ${event.level === "safe" ? "text-terminal-up" : event.level === "warning" ? "text-terminal-warn" : "text-terminal-blue"}`}>{event.level === "safe" ? <Check size={12} /> : event.level === "warning" ? <AlertTriangle size={12} /> : <Clock3 size={12} />}</span>{index < snapshot.riskEvents.length - 1 && <i className="absolute left-[9px] top-6 h-[calc(100%-9px)] border-l border-terminal-line" />}<div className="min-w-0"><p className="text-xs text-terminal-text"><span className="mr-2 font-mono text-terminal-faint">{event.time}</span>{event.title}</p><p className="mt-1 text-[11px] leading-5 text-terminal-muted">{event.detail}</p></div></li>)}</ol><div className="mt-4 border-l-2 border-terminal-down bg-terminal-down/5 p-3 text-[11px] leading-5 text-terminal-muted"><span className="font-medium text-terminal-down">隔离规则：</span>精英单源核心仓不绕过 50U 组合止损风险上限；普通单源候选仍不能形成普通共识开仓。</div></Panel>
  </div>;
}
