import { AlertTriangle, ArrowDownUp, ChevronLeft, ChevronRight, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import type { Snapshot, Trader } from "../types";
import { cn } from "../lib/utils";
import { Panel, StatusPill } from "./ui/terminal";

const sourceTone = { Bicoin: "info", OKX: "positive", Binance: "warning", Telegram: "neutral" } as const;

export function TraderLeaderboard({ snapshot }: { snapshot: Snapshot }) {
  const [query, setQuery] = useState("");
  const [source, setSource] = useState<"全部" | Trader["source"]>("全部");
  const [sort, setSort] = useState<"score" | "drawdown" | "recent">("score");
  const [page, setPage] = useState(0);
  const perPage = 12;
  const rows = useMemo(() => snapshot.traders.filter((trader) => (source === "全部" || trader.source === source) && trader.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "drawdown" ? a.drawdown - b.drawdown : b[sort] - a[sort]), [query, snapshot.traders, sort, source]);
  const maxPages = Math.max(1, Math.ceil(rows.length / perPage));
  const visible = rows.slice(page * perPage, page * perPage + perPage);
  const setPageSafe = (next: number) => setPage(Math.max(0, Math.min(maxPages - 1, next)));
  return <Panel className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-terminal-line p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="section-kicker">交易员与来源池</p><p className="mt-1 text-xs text-terminal-muted">150 名交易员 · 单人权重上限 5% · Top10 集中度上限 35%</p></div><div className="flex flex-wrap gap-2"><label className="terminal-input"><Search size={14} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="搜索交易员" /></label><select value={source} onChange={(event) => { setSource(event.target.value as typeof source); setPage(0); }} className="terminal-select"><option>全部</option>{Object.keys(sourceTone).map((item) => <option key={item}>{item}</option>)}</select><button onClick={() => setSort(sort === "score" ? "drawdown" : sort === "drawdown" ? "recent" : "score")} className="terminal-icon" title="切换排序"><ArrowDownUp size={14} /></button></div></div>
    <div className="grid border-b border-terminal-line md:grid-cols-4">{snapshot.sources.map((item) => <div key={item.name} className="flex items-center gap-2 border-b border-terminal-line p-3 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className={cn("h-1.5 w-1.5", item.status === "healthy" ? "bg-terminal-up" : "bg-terminal-warn")} /><div className="min-w-0"><p className="font-mono text-xs text-terminal-text">{item.name}</p><p className="truncate text-[10px] text-terminal-muted">{item.detail} · {item.delay}</p></div><span className="ml-auto font-mono text-[10px] text-terminal-faint">{item.records}</span></div>)}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-terminal-soft text-[10px] uppercase tracking-[0.07em] text-terminal-muted"><tr>{["交易员", "来源", "方向", "评分", "权重", "历史回撤", "稳定性", "近期表现", "延迟", "状态"].map((column) => <th key={column} className="px-3 py-2.5 font-medium">{column}</th>)}</tr></thead><tbody>{visible.map((trader) => <tr key={trader.id} className="border-t border-terminal-line/70 transition hover:bg-terminal-soft/70"><td className="px-3 py-2.5 font-medium text-terminal-text">{trader.name}</td><td className="px-3 py-2.5"><StatusPill tone={sourceTone[trader.source]}>{trader.source}</StatusPill></td><td className={cn("px-3 py-2.5 font-mono", trader.side === "long" ? "text-terminal-up" : "text-terminal-down")}>{trader.side === "long" ? "LONG" : "SHORT"}</td><td className="px-3 py-2.5 font-mono text-terminal-text">{trader.score.toFixed(3)}</td><td className="px-3 py-2.5 font-mono text-terminal-blue">{(trader.weight * 100).toFixed(1)}%</td><td className="px-3 py-2.5 font-mono text-terminal-warn">-{trader.drawdown.toFixed(1)}%</td><td className="px-3 py-2.5 font-mono text-terminal-text">{trader.stability.toFixed(2)}</td><td className={cn("px-3 py-2.5 font-mono", trader.recent >= 0 ? "text-terminal-up" : "text-terminal-down")}>{trader.recent >= 0 ? "+" : ""}{trader.recent.toFixed(1)}%</td><td className="px-3 py-2.5 font-mono text-terminal-muted">{trader.latency}</td><td className="px-3 py-2.5">{trader.status === "normal" ? <span className="text-terminal-up">正常</span> : <span className="inline-flex items-center gap-1 text-terminal-warn">{trader.status === "watch" && <AlertTriangle size={11} />} {trader.status === "watch" ? "观察" : "延迟"}</span>}</td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between border-t border-terminal-line p-3 text-[11px] text-terminal-muted"><span>显示 {page * perPage + 1}-{Math.min((page + 1) * perPage, rows.length)} / {rows.length} 名</span><div className="flex items-center gap-2"><button disabled={page === 0} onClick={() => setPageSafe(page - 1)} className="terminal-icon disabled:opacity-30"><ChevronLeft size={14} /></button><span className="font-mono">{page + 1} / {maxPages}</span><button disabled={page >= maxPages - 1} onClick={() => setPageSafe(page + 1)} className="terminal-icon disabled:opacity-30"><ChevronRight size={14} /></button></div><span className="hidden items-center gap-1 md:flex"><SlidersHorizontal size={12} />按 {sort === "score" ? "评分" : sort === "drawdown" ? "最低回撤" : "近期表现"} 排序</span></div>
  </Panel>;
}
